

version: '3'
services:
  image_rabbitmq:
    container_name: rabbitmq_server
    image: rabbitmq:3.7.8-management
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  image_app:
    container_name: app_queue_meetup
    build: ./docker/php
    ports:
      - 8085:80
    volumes:
      - ./app/:/var/www
    working_dir: /var/www
    links:
      - image_rabbitmq:rabbitmq
    command: "php -S localhost:80"

  image_worker:
    container_name: app_worker
    build: ./docker/php
    volumes:
      - ./worker/:/var/www
    working_dir: /var/www
    links:
      - image_rabbitmq:rabbitmq
    deploy:
     replicas: 3
    command: "php worker.php"


